#### <<<<<<<<<<INVESTMENTS>>>>>>>>>>
GET http://localhost:4000/investments

####
POST http://localhost:4000/investments
Content-Type: application/json

{
  "name": "Bitcoin",
  "symbol": "BTC",
  "amount": 1000,
  "price": 100000,
  "currency": "USD"
}

#### 
PUT http://localhost:4000/investments/9ca7445f-6b4b-425c-8d96-6992ca6b5223
Content-Type: application/json

{
  "amount": 1500,
  "price": 8000
}

###
DELETE http://localhost:4000/investments/00c43c20-40b1-42c7-a89a-0c328dcedd88
Content-Type: application/json

### <<<<<<<<<<< USERS >>>>>>>>>>>
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "password123"
}

### LOGIN DE UN USUARIO
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "password123"
}

### DEVOLVER INVESTMENTS DEL USUARIO LOGEADO
GET http://localhost:4000/investments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmQ1NTAxNy03MTg0LTQyNGMtOGJjNS1iOTNlZWNjNTk0ZjgiLCJpYXQiOjE3NDE3MTE2NjksImV4cCI6MTc0MTcxNTI2OX0.Pm9LW_LG8kE4jzIYLhjctQVxTHL2vprR7OkE-HkPSEU

###
POST http://localhost:4000/investments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmQ1NTAxNy03MTg0LTQyNGMtOGJjNS1iOTNlZWNjNTk0ZjgiLCJpYXQiOjE3NDE3ODczMDUsImV4cCI6MTc0MTc5MDkwNX0.NLdcNSHEwBn4gut4-QgmyBsvj0dXoIi62cUZQ6dWeZs

  {
  "name": "Bitcoin",
  "symbol": "BTC",
  "amount": 1000,
  "price": 50000,
  "currency": "USD"

}