#### <<<<<<<<<<INVESTMENTS>>>>>>>>>>
GET http://localhost:4000/investments

####
POST http://localhost:4000/investments
Content-Type: application/json

{
  "name": "Bitcoin",
  "symbol": "BTC",
  "amount": 1000,
  "price": 100000,
  "currency": "USD"
}

#### 
PUT http://localhost:4000/investments/9ca7445f-6b4b-425c-8d96-6992ca6b5223
Content-Type: application/json

{
  "amount": 1500,
  "price": 8000
}

###
DELETE http://localhost:4000/investments/00c43c20-40b1-42c7-a89a-0c328dcedd88
Content-Type: application/json

### <<<<<<<<<<< USERS >>>>>>>>>>>
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
  "name": "Ignacio sep",
  "email": "ignaciosepulveda@gmail.com",
  "password": "Contraseña123"
}

### LOGIN DE UN USUARIO
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "ignaciosepulveda@gmail.com",
  "password": "Contraseña123"
}

### DEVOLVER INVESTMENTS DEL USUARIO LOGEADO
GET http://localhost:4000/investments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmQ1NTAxNy03MTg0LTQyNGMtOGJjNS1iOTNlZWNjNTk0ZjgiLCJpYXQiOjE3NDE3ODc0NTMsImV4cCI6MTc0MTc5MTA1M30.9Bu_rn2vCthGVfHmwbqPl3DIf3Cv484c271EcxNvvIQ

###
POST http://localhost:4000/investments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmQ1NTAxNy03MTg0LTQyNGMtOGJjNS1iOTNlZWNjNTk0ZjgiLCJpYXQiOjE3NDE3ODc0NTMsImV4cCI6MTc0MTc5MTA1M30.9Bu_rn2vCthGVfHmwbqPl3DIf3Cv484c271EcxNvvIQ

  {
  "name": "Bitcoin",
  "symbol": "BTC",
  "amount": 1000,
  "price": 50000,
  "currency": "USD"

}
### USAR LA INVESTMENT_ID NO LA DEL USUARIO
###UPDATE INVESTMENT
PUT http://localhost:4000/investments/a8c0d019-1caa-4926-bb16-923231caa4c1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNmQ1NTAxNy03MTg0LTQyNGMtOGJjNS1iOTNlZWNjNTk0ZjgiLCJpYXQiOjE3NDE3ODk0NDAsImV4cCI6MTc0MTg3NTg0MH0.1FxoAV2U3yW_JjqXuqumjo0jaVOQ6ZS_xeVCiYzEAUs

{
  "amount": 15
}