####
GET http://localhost:4000/investments

####
POST http://localhost:4000/investments
Content-Type: application/json

{
  "name": "Ethereum",
  "symbol": "ETH",
  "amount": 1000,
  "price": 2200,
  "currency": "USD"
}
